Added About Mohit
pclubuiet/Hacktoberfest-2k17 pull request #26
Opened 2017-10-12 13:03 UTC by nagpalm7

I've added information about myself

2017-10-12 13:04 UTC, azharcaptain20 requested changes

2017-10-12 13:04 UTC, azharcaptain20 commented on submissions/nagpalm7/about.md
> +
Remove extra lines

2017-10-12 13:10 UTC, nagpalm7 commented
I've made the changes. Please review

2017-10-12 15:19 UTC, divyam3897 requested changes
Write a good commit message and contact info should not be in same line.

2017-10-15 18:56 UTC, divyam3897 commented
closing as duplicate.

2017-10-15 18:56 UTC, closed without merging