Added Ishaan0905 details
pclubuiet/Hacktoberfest-2k17 pull request #3
Opened 2017-10-11 16:16 UTC by Ishaan0905

I have added my info.

2017-10-11 20:28 UTC, divyam3897 requested changes

2017-10-11 20:28 UTC, divyam3897 commented on submissions/Ishaan0905/about.md
> +I am a Student at UIET(Best Experience)
full stop missing at the end of sentence.

2017-10-11 20:28 UTC, divyam3897 commented on submissions/Ishaan0905/about.md
> +Open source, Gaming, Food
Full stop

2017-10-11 20:31 UTC, divyam3897 commented
@Ishaan0905 as told commit message should be in present tense.

2017-10-12 15:25 UTC, Ishaan0905 commented
I have made the required changes

2017-10-12 19:28 UTC, divyam3897 requested changes
Remove empty lines and squash  your commits into one.

2017-10-16 08:36 UTC, Ishaan0905 commented
Please review.

2017-10-26 11:36 UTC, closed without merging