Solve #33
pclubuiet/Hacktoberfest-2k17 pull request #34
Opened 2017-10-12 15:58 UTC by Mahirgupta

Remove empty lines from divyam3897. (Solve #33)

2017-10-12 19:17 UTC, divyam3897 requested changes
All contact info is not on next lines.

2017-10-13 07:51 UTC, divyam3897 requested changes
Just change the commit message and write a good one and it's good to be merged.

2017-10-13 16:14 UTC, sagar-kalra requested changes

2017-10-13 16:14 UTC, sagar-kalra commented on submissions/mahirgupta/about.md
> +<<<<<<< HEAD
remove these conflicts

2017-10-13 16:14 UTC, sagar-kalra commented on submissions/divyam3897/about.md
remove this extra line.

2017-10-14 13:28 UTC, divyam3897 commented
Fixed in https://github.com/pclubuiet/Hacktoberfest-2k17/commit/83595182d1750e6d43f65943d71a129c497b9f05

2017-10-14 13:28 UTC, closed without merging