Add about pareksha
pclubuiet/Hacktoberfest-2k17 pull request #57
Opened 2017-10-14 06:09 UTC by pareksha

2017-10-14 06:20 UTC, divyam3897 requested changes
Contact infos not in different lines.

2017-10-14 06:46 UTC, pareksha commented
Sir,
Kindly review the PR again. Changes have been made in the same PR.
Regards,
Pareksha

On 14 Oct 2017 11:50 am, "Divyam Madaan" <notifications@github.com> wrote:

*@divyam3897* requested changes on this pull request.

Contact infos not in different lines.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pclubuiet/Hacktoberfest-2k17/pull/57#pullrequestreview-69385109>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/Ae4pf4SEJqzqX05CFwSmsa_XVP7Wh6zDks5ssFKpgaJpZM4P5Rjv>
.

2017-10-14 07:00 UTC, divyam3897 requested changes

2017-10-14 07:00 UTC, divyam3897 commented on submissions/parekshamanchanda/about.md
> +My favorite emoji is :smile:
full stop after the end of sentence.

2017-10-14 07:11 UTC, pareksha commented
Changes have been made. Kindly, review PR again.

On 14 Oct 2017 12:30 pm, "Divyam Madaan" <notifications@github.com> wrote:

> *@divyam3897* requested changes on this pull request.
> ------------------------------
>
> In submissions/parekshamanchanda/about.md
> <https://github.com/pclubuiet/Hacktoberfest-2k17/pull/57#discussion_r144688219>
> :
>
> > @@ -0,0 +1,12 @@
> +# About Me
> +My name is Pareksha Manchanda. I am a CSE student at Panjab University, India.
> +# Experience
> +No experience yet.
> +# Interests
> +Python, Android.
> +# Contact Info
> +Email: pareksha.manchanda@gmail.com
> +Github: pareksha
> +Facebook Profile: Pareksha Manchanda
> +# Emoji
> +My favorite emoji is :smile:
>
> full stop after the end of sentence.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pclubuiet/Hacktoberfest-2k17/pull/57#pullrequestreview-69385732>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ae4pfz8MEQemOSnvgK1YE4-cAEQq5ABCks5ssFwUgaJpZM4P5Rjv>
> .
>

2017-10-14 10:53 UTC, gurpreetsingh00885 requested changes

2017-10-14 10:53 UTC, gurpreetsingh00885 commented on submissions/parekshamanchanda/about.md
> +Email: pareksha.manchanda@gmail.com
Wrong format for E-mail.

2017-10-14 10:53 UTC, gurpreetsingh00885 commented on submissions/parekshamanchanda/about.md
> +Github: pareksha
Wrong format for adding a link.

2017-10-14 10:53 UTC, gurpreetsingh00885 commented on submissions/parekshamanchanda/about.md
> +Facebook Profile: Pareksha Manchanda
same

2017-10-15 04:57 UTC, ghost approved these changes

2017-10-15 04:58 UTC, merged